version: '3'
services:

  mysql:
    container_name: 'db_shopper'
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    tty: true
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "shopperDB"
    expose:
      - '3306'
    ports:
      - '3306:3306'
    networks:
      - network-shopper

networks:
  network-shopper:
    driver: bridge